CREATE TABLE TB_USER (
	ID INTEGER PRIMARY KEY,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE TB_USER_ROLE (
	USER_ID INTEGER NOT NULL PRIMARY KEY,
	ROLE VARCHAR(50)
);
ALTER TABLE TB_USER_ROLE ADD CONSTRAINT TB_USER_ROLE_UNQ UNIQUE (USER_ID, ROLE);

CREATE SEQUENCE TB_AUTHORITY_ID_SEQ START 1;
CREATE TABLE TB_AUTHORITY (
    ID INTEGER DEFAULT NEXTVAL('TB_AUTHORITY_ID_SEQ'),
    NAME VARCHAR(100) NOT NULL,
    SHORT_NAME VARCHAR(5) NOT NULL,
    PRIMARY KEY (ID)
)

CREATE TABLE TB_USER_AUTHORITY (
    USER_ID INTEGER NOT NULL,
    AUTHORITY_ID INTEGER NOT NULL
)
ALTER TABLE TB_USER_AUTHORITY ADD FOREIGN KEY FK_USER_TB_USER_AUTHORITY (USER_ID) REFERENCES TB_USER(ID);
ALTER TABLE TB_USER_AUTHORITY ADD FOREIGN KEY FK_AUTHORITY_TB_USER_AUTHORITY (AUTHORITY_ID) REFERENCES TB_AUTHORITY (ID);
ALTER TABLE TB_USER_AUTHORITY ADD CONSTRAINT TB_USER_AUTHORITY_UNQ (USER_ID, AUTHORITY_ID);
