CREATE TABLE TB_USER (
	ID INTEGER PRIMARY KEY,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE TB_USER_ROLE (
	USER_ID INTEGER NOT NULL PRIMARY KEY,
	ROLE VARCHAR(50)
);
ALTER TABLE TB_USER_ROLE ADD CONSTRAINT TB_USER_ROLE_UNQ UNIQUE (USER_ID, ROLE);